server:
  port: 18082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.128:3306/guli_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: jjjj
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  redis:
    host: 192.168.136.128
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
feign:
  sentinel:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.sms.entity
  mapper-locations: classpath:mapper/sms/*.xml  # \u8BFB\u53D6\u6620\u5C04\u6587\u4EF6